# Generated by Django 3.0.7 on 2020-06-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('prduct_code', models.CharField(max_length=40)),
                ('memory_type', models.CharField(choices=[('2', 'DDR2'), ('3', 'DDR3'), ('4', 'DDR4')], max_length=1)),
                ('size', models.CharField(choices=[('2', '2GB'), ('4', '4GB'), ('8', '8GB'), ('16', '16GB'), ('32', '32GB'), ('64', '64GB'), ('124', '124GB')], max_length=3)),
                ('frequency', models.CharField(max_length=4)),
                ('voltage', models.CharField(max_length=6)),
            ],
        ),
    ]
