# Generated by Django 3.0.7 on 2020-06-16 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20200616_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ram',
            name='prduct_code',
            field=models.SlugField(max_length=40),
        ),
    ]
