# Generated by Django 3.0.7 on 2020-06-16 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20200616_1239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ram',
            old_name='prduct_code',
            new_name='product_code',
        ),
    ]
